[package]
name = "hello"
version = "0.1.0"
authors = ["prisbe"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"pcap"="*"
chrono = "0.4"
eframe = "0.15.0"
egui = "0.15.0"
emath = "0.15.0"
